### ISSUE TITLE
Secret Manager SDK for node?

### ISSUE THREAD

**Issue by ricky11** [aliyun/alibabacloud-secretsmanager-client-java#6]
Hello i would to know how to use secret manager or FUNCTION COMPUTE (nodejs)

thank you.

**Comment by yinhudongtian** [comment]
you cloud use secret manager by [kms nodejs sdk](https://www.npmjs.com/package/@alicloud/kms?spm=a2chm.sdk.0.0.5b997bbba9aVL4)
